### ISSUE TITLE
Deprecate tessellate-viewer in favour of Tailor

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/tessellate#101]
tessellate-view tries to fulfil the same purpose as [Tailor](https://github.com/zalando/tailor/) but is less complete and useful at the same time.

We should deprecate and remove tessellate-viewer from this repository and provide a complete example with Tailor instead. See https://github.com/mfellner/tessellate-mosaic-demo for an example of that.

**Comment by mfellner** [comment]
Closed in https://github.com/zalando-incubator/tessellate/commit/33b8a25a203a5c1906bd03b395d0c6cc966ff8d1

**Comment by swistaczek** [comment]
Hey @mfellner :)! Thanks for great contribution. Is there any chance to update provided demo repository for current version of tessellate? Have a great day!
