### ISSUE TITLE
Create tessellate-request package for authorised requests

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/tessellate#40]
Create a new package tessellate-request, that:

* provides a configurable, easy to use HTTP request client to tessellate services
* uses [request-promise-native](https://github.com/request/request-promise-native)
* integrates OAUTH2 support via [bearer authentication](https://github.com/request/request#http-authentication) and [client-oauth-2](https://www.npmjs.com/package/client-oauth2)
* makes OAUTH2 authentication configurable via nconf (or the tessellate-config package #41):
  - scheme (e.g. resource owner password credentials)
  - client-id
  - client-secret
  - username
  - password
  - access token URI
  - scopes
* matches different authentication schemes to respective domains (or base URLs)

**Comment by mfellner** [comment]
@semonte tessellate-request was already created. Are there any bullet points from this issue not yet implemented? Otherwise I would close this issue.

**Comment by semonte** [comment]
>makes OAUTH2 authentication configurable via nconf 

Only Zalando OAuth2 authentication configuration is currently supported (= read credentials in Taupage to get access tokens).

> matches different authentication schemes to respective domains (or base URLs)

This was not implemented. Authentication schemes are mapped by IDs.

**Comment by mfellner** [comment]
Requests will be merged into tessellate-server as described in #87

**Comment by mfellner** [comment]
Labelling as wontfix because of major changes in https://github.com/zalando-incubator/tessellate/pull/96.
