### ISSUE TITLE
example-bundle generates invalid fragment code in index.js

### ISSUE THREAD

**Issue by semonte** [zalando-incubator/tessellate#46]
In `example-bundle`

1) `npm run webpack`
2) `npm start`

Using the uploaded `index.js` in tessellate-fragment returns the following error:

```
ReferenceError: console is not defined at warn
```

Commenting `console.warn` in index.js fixes the issue. For a permanent fix, console calls should be removed when building or the calls should be made safe.

**Comment by mfellner** [comment]
Closing this issue because the example-bundle was removed from the repository. We also do not recommend writing bundles by hand (although I kept the code and it lives on as a private repository for now).
