### ISSUE TITLE
Fragment rendering fails when included in Tailor

### ISSUE THREAD

**Issue by semonte** [zalando-incubator/tessellate#50]
tessellate-fragment assumes the following value format for `x-zalando-request-uri` HTTP header:

`https://www.zalando.de/foo`

However, when the fragment is requested by Tailor, the following header is sent for `https://www.zalando.de/foo`:

`x-zalando-request-uri: /foo`

Parsing this value fails and the fragment is not rendered.

**Comment by mfellner** [comment]
Fixed in #51
