### ISSUE TITLE
Add support for multi-core systems (tessellate-fragment)

### ISSUE THREAD

**Issue by semonte** [zalando-incubator/tessellate#70]
`tessellate-fragment` does not scale vertically at all. Many EC2 instances provide multiple CPUs, but we get no benefit from that.

I suggest adding clustering support for `tessellate-fragment` as documented in https://nodejs.org/api/cluster.html

**Comment by mfellner** [comment]
We'll need to add this feature to tessellate-server and then base tessellate-fragment on that (https://github.com/zalando-incubator/tessellate/issues/38).
